---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: rest-json-quickstart
  name: rest-json-quickstart
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: rest-json-quickstart
  template:
    metadata:
      labels:
        app.kubernetes.io/name: rest-json-quickstart
    spec:
      containers:
        - name: rest-json-quickstart
          image: {{ .Values.app.image }}
          imagePullPolicy: Always
          ports:
            - containerPort: {{ .Values.app.ports.http }}
              name: http
              protocol: TCP
