apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    nginx.org/mergeable-ingress-type: minion
  name: rest-json-quickstart
spec:
  ingressClassName: nginx
  rules:
    - host: {{ .Values.app.host }}
      http:
        paths:
          - backend:
              service:
                name: rest-json-quickstart
                port:
                  name: http
            path: /app
            pathType: Prefix
