name: Publish Helm Chart

on:
  push:
    branches: [ main, rest-json-quickstart ]
    # Monitor changes to any chart files at the root level
    paths:
      - 'Chart.yaml'
      - 'values.yaml'
      - 'templates/**'
      - '.helmignore'
  # Allow manual triggering
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    
    permissions:
      contents: read
      packages: write
      
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        
      - name: Set up Helm
        uses: azure/setup-helm@v3
        with:
          version: 'latest'
      
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Save and Push Helm Chart
        run: |
          CHART_PATH=charts/mychart  # Adjust to your chart folder
          CHART_NAME=$(helm show chart $CHART_PATH | grep '^name:' | awk '{print $2}')
          CHART_VERSION=$(helm show chart $CHART_PATH | grep '^version:' | awk '{print $2}')
          OCI_REF=ghcr.io/${{ github.repository }}/$CHART_NAME:$CHART_VERSION

          # Save the chart as an OCI artifact
          helm package $CHART_PATH
          helm push $CHART_NAME-$CHART_VERSION.tgz oci://ghcr.io/${{ github.repository }}
