name: Publish Helm Chart

on:
  push:
    branches: [ main, rest-json-quickstart ]
    # Monitor changes to any chart files at the root level
    paths:
      - 'Chart.yaml'
      - 'values.yaml'
      - 'templates/**'
      - '.helmignore'
  # Allow manual triggering
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    
    permissions:
      contents: read
      packages: write
      
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        
      - name: Set up Helm
        uses: azure/setup-helm@v3
        with:
          version: 'latest'
      
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Package and Push Helm Chart
        run: |
          # Set variables
          CHART_DIR="."  # Chart is at root level
          CHART_NAME=$(yq e '.name' $CHART_DIR/Chart.yaml)
          CHART_VERSION=$(yq e '.version' $CHART_DIR/Chart.yaml)
          REGISTRY="ghcr.io/${{ github.repository_owner }}"
          
          echo "Publishing $CHART_NAME chart version $CHART_VERSION to $REGISTRY"
          
          # Package the chart locally
          helm package $CHART_DIR
          
          # Push the chart to GitHub Packages
          helm push ${CHART_NAME}-${CHART_VERSION}.tgz oci://$REGISTRY/helm-charts
