name: Publish Helm Chart to GitHub Container Registry (GHCR)

on:
  push:
    branches:
      - rest-json-quickstart
    paths:
      - '**'  # (Optional) You can restrict this if needed

jobs:
  publish-chart:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Helm
        uses: azure/setup-helm@v3
        with:
          version: v3.14.0

      - name: Login to GitHub Container Registry
        run: |
          echo "${{ secrets.GITHUB_TOKEN }}" | helm registry login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Save and Push Helm Chart as OCI
        run: |
          CHART_DIR=.
          CHART_NAME=$(helm show chart $CHART_DIR | grep '^name:' | awk '{print $2}')
          CHART_VERSION=$(helm show chart $CHART_DIR | grep '^version:' | awk '{print $2}')
          OCI_REPO=ghcr.io/${{ github.repository }}/$CHART_NAME

          # Save and Push
          helm chart save $CHART_DIR $OCI_REPO:$CHART_VERSION
          helm chart push $OCI_REPO:$CHART_VERSION
